In [2]:
import pandas as pd
import numpy as np

### **Notes**
- **Skewness:** a measure of the asymmerty of a distribution around its mean.
- **Excess Kurtosis:** a measure of the tail heaviness and peakedness relative to a normal distribution.

For a Gaussian distribution, both are zero.

In [7]:
n_samples = 5000

data = pd.DataFrame({
    'X' : np.random.lognormal(mean=0.0, sigma=1.0, size=n_samples),
    'Y' : np.random.gamma(shape=1, scale=1, size=n_samples)
})

results = pd.DataFrame()
results['Skewness'] = data.skew()
results['Excess kurtosis'] = data.kurtosis()

display(results)

   Skewness  Excess kurtosis
X  6.640646        89.522741
Y  1.902885         4.884309

In [11]:
epsilon = 1e-6
log_data = data.copy()
log_data = log_data.apply(lambda x: np.log(x + epsilon))

results = pd.DataFrame()
results['Skewness'] = log_data.skew()
results['Excess kurtosis'] = log_data.kurtosis()

display(results)

   Skewness  Excess kurtosis
X  0.018094        -0.046497
Y -1.220216         2.657450

In [13]:
from sklearn.preprocessing import PowerTransformer

box_cox_data = data.copy()
transformer = PowerTransformer(method='box-cox')
box_cox_data.loc[:] = transformer.fit_transform(box_cox_data)

results = pd.DataFrame()
results['Skewness'] = box_cox_data.skew()
results['Excess kurtosis'] = box_cox_data.kurtosis()

display(results)

   Skewness  Excess kurtosis
X  0.000102        -0.049215
Y -0.038930        -0.268708

### **Conclusion**
- Log transform good for approximately log-normally distributed data.
- Box-Cox (or Yeo-Johnson) transform works well for any general distribution like Beta, Gamma, Log-normal, etc.